import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "../components/Navbar";
import SidebarNavigation from "../components/Sidebar";
import QueryProvider from "@/Provider/QueryProvider";
import NextProgressBar from "@/Provider/NextProgressBar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextProgressBar>
          <QueryProvider>
            <Navbar />
            <div className="flex w-full">
              <SidebarNavigation />
              <div className="flex-1 overflow-x-auto">
                {children}
              </div>
            </div>
          </QueryProvider>
        </NextProgressBar>
      </body>
    </html>
  );
}
